[package]
name = "umber"
version = "0.5.1"
edition = "2024"
authors = ["Ivan Porto Carrero"]
description = "cat with syntax highlighting - a modern replacement for cat with tree-sitter powered syntax highlighting"
license = "MIT"
repository = "https://github.com/casualjim/umber"
homepage = "https://github.com/casualjim/umber"
readme = "README.md"
keywords = ["cat", "syntax-highlighting", "cli", "terminal", "tree-sitter"]
categories = ["command-line-utilities", "text-processing"]

[package.metadata.release]
sign-commit = false
sign-tag = false
publish = false
allow-branch = ["main"]
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
clap_mangen = "0.2"
crossterm = "0.29"
dark-light = { git = "https://github.com/rust-dark-light/dark-light", branch = "main" }
eyre = "0.6"
once_cell = "1.19"
palate = "0.3.6"
shlex = "1.3"
syntastica = { git = "https://github.com/casualjim/syntastica", branch = "expand-languages-git-deploy" }
syntastica-highlight = { git = "https://github.com/casualjim/syntastica", branch = "expand-languages-git-deploy" }
syntastica-parsers-git = { git = "https://github.com/casualjim/syntastica", branch = "expand-languages-git-deploy", features = ["all"] }
syntastica-query-preprocessor = { git = "https://github.com/casualjim/syntastica", branch = "expand-languages-git-deploy" }
syntastica-themes = { git = "https://github.com/casualjim/syntastica", branch = "expand-languages-git-deploy" }

git2 = { version = "0.20", default-features = false }
similar = { version = "2.6", default-features = false, features = ["text"] }

[target.'cfg(target_os = "linux")'.dependencies]
zbus = "5.13.2"
zvariant = "5.9.2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
